name: MacOS Conda build

on:
#   push:
#     branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  conda_version: 4.7.5
  conda_build_version: 3.18

jobs:
  Linuxjob:
    name: "Linuxjob ${{ matrix.python_version }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python_version: [36, 37, 38, 39]
    steps:
      - uses: actions/checkout@v2
        name: Checkout 

      - name: Add conda to PATH
        shell: bash
        run: echo "$CONDA/bin" >> $GITHUB_PATH

      - name: "Creating updated environment with conda-build..."
        shell: bash
        run: |
          echo "conda_version: $conda_version"
          echo "conda_build_version: $conda_build_version"
          which conda
          conda -V
          conda info
          source activate
          conda update --yes conda
          conda create --yes --quiet --name bld --no-default-packages
          conda install --yes --name bld conda-build
          
      - name: "Building conda package..."
        shell: bash
        run: |          
          set -x
          source activate bld
          ${LINUX32} conda build --python ${{ matrix.python_version }} --output-folder channel recipe

      - uses: actions/upload-artifact@v2
        with:
          name: AnacondaPackage
          path: "${{github.workspace}}/channel/*/simpleitk*.tar.bz2"

  MacOSjob:
    name: "MacOSjob ${{ matrix.python_version }}"
    runs-on: macos-latest
    strategy:
      matrix:
        python_version: [36, 37, 38, 39]
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.15'
    steps:
      - uses: actions/checkout@v2
        name: Checkout 
      - name: Take ownership of conda installation
        run: sudo chown -R $USER $CONDA
        shell: bash 
      - name: Add conda to PATH
        shell: bash
        run: echo "$CONDA/bin" >> $GITHUB_PATH
      - name: "Creating updated environment with conda-build..."
        shell: bash
        run: |
          set -x
          sudo xcode-select --switch /Applications/Xcode_11.7.0.app
          xcode-select -p
          echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk"
          curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
          tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
          cat << EOF >> ${GITHUB_WORKSPACE}/conda_build_config.yml
          CONDA_BUILD_SYSROOT:
             - $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk
          MACOSX_DEPLOYMENT_TARGET:
             - ${MACOSX_DEPLOYMENT_TARGET}
          EOF
          cat << EOF > ~/.condarc
          conda_build:
            config_file: ${GITHUB_WORKSPACE}/conda_build_config.yml
          EOF
          
          source activate
          conda update --yes conda
          conda create --yes --quiet --name bld --no-default-packages
          conda install --yes --name bld conda-build
      - name: "Building conda package..."
        shell: bash
        run: |
          export PYTHONUNBUFFERED=1
          set -x
          source activate bld
          conda build --python ${{ matrix.python_version }}  --output-folder channel recipe
      - uses: actions/upload-artifact@v2
        with:
          name: AnacondaPackage
          path: "${{github.workspace}}/channel/*/simpleitk*.tar.bz2"
