name: MacOS Conda build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  conda_version: 4.7.5
  conda_build_version: 3.18

jobs:
  MacOSjob:
    runs-on: macos-latest
#     runs-on: macos-latest
    strategy:
      matrix:
#         python_version: [3.6, 3.7, 3.8, 3.9]
        python_version: [39]
    env:
      MACOSX_DEPLOYMENT_TARGET: '10.9'
    steps:
      - uses: actions/checkout@v2
        name: Checkout 
      - name: Take ownership of conda installation
        run: sudo chown -R $USER $CONDA
        shell: bash 
      - name: Add conda to PATH
        shell: bash
        run: echo "$CONDA/bin" >> $GITHUB_PATH
#       - name: "test environment with conda-build..."
#         shell: bash
#         run: |
#           set -x
#           xcode-select -p
#           ls -l /Applications/Xcode*
#           ls -l /Applications
#           sudo xcode-select --switch /Applications/Xcode_11.7.0.app
#           xcode-select -p
#           xcodebuild -version


      - name: "Creating updated environment with conda-build..."
        shell: bash
        run: |
          set -x
          ls -l
          pwd
          echo $USER $CONDA
          ls -l $CONDA
          ls -l $CONDA/bin
          echo "GITHUB_WORKSPACE ---- $GITHUB_WORKSPACE"
          xcode-select -p
          ls -l /Applications/Xcode*
          ls -l /Applications
          # sudo xcode-select --switch /Applications/Xcode_11.7.0.app
          sudo xcode-select --switch /Applications/Xcode_12.4.app
          xcode-select -p
          # ${GITHUB_WORKSPACE}/.azure-pipelines/support/osx_install_sdk.sh
          echo "Downloading ${MACOSX_DEPLOYMENT_TARGET} sdk"
          curl -L -O https://github.com/phracker/MacOSX-SDKs/releases/download/10.15/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz
          tar -xf MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk.tar.xz -C "$(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs"
          cat << EOF >> ${GITHUB_WORKSPACE}/conda_build_config.yml
          CONDA_BUILD_SYSROOT:
             - $(xcode-select -p)/Platforms/MacOSX.platform/Developer/SDKs/MacOSX${MACOSX_DEPLOYMENT_TARGET}.sdk
          MACOSX_DEPLOYMENT_TARGET:
             - ${MACOSX_DEPLOYMENT_TARGET}
          EOF

          cat << EOF > ~/.condarc
          conda_build:
            config_file: ${GITHUB_WORKSPACE}/conda_build_config.yml
          EOF
          
          source activate
          conda update --yes conda
          conda create --yes --quiet --name bld --no-default-packages
          conda install --yes --name bld conda-build
      - name: "Building conda package..."
        shell: bash
        run: |
          export PYTHONUNBUFFERED=1
          set -x
          source activate bld
          conda build --python ${{ matrix.python_version }}  --output-folder channel recipe
