name: Linux Conda t2

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  conda_version: 4.7.10
  conda_build_version: 3.18

jobs:
  Linuxjob:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#         python_version: [3.6, 3.7, 3.8, 3.9]
        python_version: [3.9]
    steps:
      - name: Conda info 00
        shell: bash
        run: |
          set -x
          which cmake
          cmake --version
          which conda
          echo "PATH: $PATH"
          echo "CONDA: $CONDA"
          echo "conda_version: $conda_version"
          conda info
          conda list
          conda config --show-sources
          conda config --show

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: ${{env.conda_version}}
          conda-build-version: ${{env.conda_build_version}}
          python-version: ${{ matrix.python-version }}
      - name: Conda info
        shell: bash
        run: |
          which conda
          echo "PATH: $PATH"
          echo "CONDA: $CONDA"
          echo "conda_version: $conda_version"
          conda info
          conda list
          conda config --show-sources
          conda config --show
      - name: Add conda to PATH
        shell: bash
        run: echo "$CONDA/bin" >> $GITHUB_PATH
      - name: "Creating updated environment with conda-build..."
        shell: bash
        run: |
          which conda
          source activate
          conda update --yes conda
      - name: Conda info 11
        shell: bash
        run: |
          which conda
          echo "PATH: $PATH"
          echo "CONDA: $CONDA"
          echo "conda_version: $conda_version"
          conda info
          conda list
          conda config --show-sources
          conda config --show
