name: Python Package Using Anaconda

on: 
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
#     runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        # $CONDA/bin/conda env update --file environment.yml --name base
        echo "CONDA: $CONDA"
        ls -lr $CONDA
        echo $PATH
        which conda
    - run: |
        which conda
        conda info
        conda list
