---
name: CI

on:
  # push:
  #   branches: ["master"]
  # pull_request:
  #   branches: ["master"]
  workflow_dispatch:
env: 
  myenv1: 'luwe-hi'
jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
#     runs-on: "self-hosted"
    runs-on: "ubuntu-latest"
    env:
      USING_COVERAGE: '3.8'
      # USING_COVERAGE: '3.6,3.8'

    strategy:
      matrix:
        # python-version: ["3.6", "3.7", "3.8", "pypy3"]
        python-version: ["3.8"]

    steps:
      - uses: "actions/checkout@v2"
      
      - name: "checking "     
        run: |
           echo "CONDA: $CONDA"  
           ls -l $CONDA/bin
          
      - uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
          
      - name: "checking2 "     
        run: |
           echo "CONDA: $CONDA"  
           ls -l $CONDA/bin
           
      - name: "Install dependencies"
        run: |
          set -xe
          cat /etc/os-release
          df -h
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade coverage[toml] virtualenv tox tox-gh-actions          



      - name: "echo env"
        run: "echo $myenv1 $USING_COVERAGE ${{ matrix.python-version }} "

      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          activate-environment: foo
     
      - name: "checking3 "     
        run: |
           echo "CONDA: $CONDA"  
           ls -l $CONDA/bin     
          
      # - name: "Run tox targets for ${{ matrix.python-version }}"
      #   run: "python -m tox"
#       - name: Setup conda
#         uses: s-weigand/setup-conda@v1
#         with:
#           update-conda: true
#           python-version: ${{ matrix.python-version }}
#           conda-channels: anaconda, conda-forge
#       - run: conda --version
#       - run: which python
          
#       - name: Install dependencies
#         run: |
#           # $CONDA is an environment variable pointing to the root of the miniconda directory
#           # $CONDA/bin/conda env update --file environment.yml --name base
#           echo "CONDA: $CONDA"    
      
      - name: Conda info
#         shell: bash -l {0}  # activate the conda environment
        run: |
          conda info
          conda list
          

